### ISSUE TITLE
Incorrect Controller Mapping

### ISSUE THREAD

**Issue by SavnoorSamra** [thestr4ng3r/chiaki#24]
Tested on both Linux and Windows 10
Xbox 360 Controller with a wireless adapter and Dualshock over USB on Windows and Bluetooth on Ubuntu 18 have square and triangle swapped. Changing mappings in PS4 accessibility also does not seem to make a difference. This is a simple fix and is preventing me from using this application.

**Comment by rgcv** [comment]
Did you build Chiaki from source? If so, this might still be an issue.

However, you might wanna take a look at #5. The issue you're having seems to have been fixed as well in the commit it's being referenced from (2e752ea). This commit wasn't included in 1.0.2.

Try running a source build instead and see if the issue still persists.

**Comment by SavnoorSamra** [comment]
@rgcv yeah actually I opened that other issue to but the dev closed it and the issue is still present. Can you please explain how to run a source build on windows? Also do you know when will the next release come?

**Comment by rgcv** [comment]
@SavnoorSamra Oh yeah, that's you! Woops, my bad 😂

I haven't run a source build on Windows yet, and I've only built it on Arch from the release sources, but I can give you a rough guideline. **Be warned**: I haven't tested this whatsoever.

1. Gather the required dependencies, outlined in the README file:
   - [CMake](https://cmake.org/download/#latest)
   - [Qt5](https://doc.qt.io/qt-5/windows.html) -- with Multimedia, SVG, and OpenGL
   - [FFMPEG](https://ffmpeg.zeranoe.com/builds/)
   - [libopus](https://opus-codec.org/downloads/)
   - [OpenSSL](https://slproweb.com/products/Win32OpenSSL.html) >= 1.1
   - [protoc](https://github.com/protocolbuffers/protobuf/releases/latest)
   - protobuf bindings for python which can be obtained using pip which comes bundled with the [Python](https://www.python.org/downloads/release/python-374/) Windows installer

2. You'll need [git](https://git-scm.com/downloads) for this too for some third-party libs, referenced as submodules.

3. Despite all this, you might need Microsoft's Visual C/C++ compiler (MSVC), which comes bundled with the [Visual Studio](https://visualstudio.microsoft.com/downloads/). You can get just the tools without the IDE now too, which is nice, I guess. Alternatively, try [Mingw](https://osdn.net/projects/mingw/releases/#preferred-files-wrap), either directly or through [Cygwin](https://cygwin.com/install.html).

4. Clone the repo and init + update the submodules, i.e.,

```sh
git clone https://github.com/thestr4ng3r/chiaki.git
cd chiaki
git submodule update --init
```

4. Make sure the dependencies required outlined in steps 1 and 3 are reachable to CMake (which, in Windows, generally means being in the `PATH` environment variable, for simplicity's sake--that means binaries and `.dll`s).

5. Then, you can either use CMake GUI, or use CMake via the command line and issue the commands again mentioned in the README file

   5.1. With CMake GUI, you just set the source and build directories, press configure, choose a generator, which will depend on the compiler toolchain chosen in step 3. Then, you build it--with Visual Studio, open the generated solution and run `ALL_BUILD`; with Mingw, just run `make` inside the build directory.

6. You should be done! The artifacts should be somewhere inside the build directory, ready for you to run them.

Once again, I haven't tested this, and by now, you can already tell this is a hefty thing to do. This is where pre-packed containers and cross-compilation do wonders, making you avoid all of this setup. HOWEVER, this sounds a bit silly, IMHO, and it is far easier to do on Linux. If you'd just like to test the button mapping issue, I strongly recommend you choose Linux for that purpose. Moreso, I recommend Arch. I'm pondering publishing a `git` AUR package eventually, just haven't gotten around to it.

**Comment by SavnoorSamra** [comment]
@rgcv wow thanks for the great instructions! I tried this but my sad little chrome book running ubuntu ran out of space while compiling protoc. I will try creating a vm with arch Linux and see if it works. But I can do it on windows though right?

**Comment by rgcv** [comment]
@SavnoorSamra don't mention it! Also, I expected Ubuntu to have most, if not all, of the required software in their repos.. hmm, can't tell, but no big deal.

The instructions are a bit windows specific, but can easily be adapted for a Linux environment. You can trim a lot of details because of package management and availability, and how easy it is to develop and compile software in a Linux environment.

On Windows, unfortunately, that isn't quite the case. Albeit not an impossible task, it is quite more cumbersome.

**Comment by SavnoorSamra** [comment]
@rgcv yes I was forced to manually compile protoc but I have only have 16gb of storage on my laptop and that's the main device I want to use chiaki on so I will have to find some kind of a fix soon. I just don't want to spend so much time compiling it just to find out the controller is still buggy. Is it possible you can create an app image file for me? I have never messed around with source code before so I don't know how it works.

**Comment by thestr4ng3r** [comment]
For Windows, you can try the artifact here: https://ci.appveyor.com/project/thestr4ng3r/chiaki/builds/27237089/artifacts Please try this and confirm whether or not it works for you.
Travis doesn't provide artifacts like that so you will have to wait until the next release or build from source for Linux.
Also please try to avoid opening issues for the same problem more than once. If an issue still persists after closing, you can always comment on the closed one. Thanks!

**Comment by SavnoorSamra** [comment]
@thestr4ng3r thanks!

**Comment by SavnoorSamra** [comment]
@thestr4ng3r okay so I tried the artifact and controller is fine. So when will you make a new release?

**Comment by thestr4ng3r** [comment]
After I fixed a few more Windows issues, so probably around next week. Thanks for testing!

**Comment by rgcv** [comment]
Glad to see things are working :wink:
